### ISSUE TITLE
Hidden tabs can get unhidden

### ISSUE THREAD

**Issue by DavidRegev** [AbigailBuccaneer/firefox-ctrlnumber#1]
The extension doesn’t take into account that some tabs may be hidden. Instead of ignoring tabs that are not currently visible, it counts through all tabs, both visible and hidden.

**Steps to reproduce:**
1. Install an extension that hides tabs, such as [Simple Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) or [Hide Tabs](https://addons.mozilla.org/en-US/firefox/addon/hide-tab/). 
1. Open more than one tab.
1. Right click on the last tab and hide it (or move it to a different group).
1. Press `Ctrl+9`.

**Expected results:** The last _visible_ tab is active.
**Actual results:** The hidden tab is unhidden and active, since that was the last tab before it was hidden.

Note that this bug doesn’t occur using the built-in `Alt+#`.

Thanks!

**Comment by jtagcat** [comment]
I'm the maintainer of [Ctrl, not Alt](https://gitlab.com/jtagcat/ctrl-not-alt), where this issue has been closed.

**Comment by DavidRegev** [comment]
> I'm the maintainer of [Ctrl, not Alt](https://gitlab.com/jtagcat/ctrl-not-alt), where this issue has been closed.

Thanks! I tested it and it's working so far.

**Comment by jtagcat** [comment]
You may subscribe to https://gitlab.com/jtagcat/ctrl-not-alt/issues/1
If it is closed, the extension will be also released to the Firefox Add-ons platform. That way, you get updates to the extension.

**Comment by AbigailBuccaneer** [comment]
Thanks for the report! This is now fixed in v1.0.1.
